server:
  port: 9000
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/cat_1
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver